api:
  image:
    repository: 296725355870.dkr.ecr.ap-southeast-1.amazonaws.com/quyen-simpleauth-api
  jwtSecret: your-strong-secret-at-least-32-characters-long
  imagePullSecrets:
    - name: ecr-secret

ui:
  image:
    repository: 296725355870.dkr.ecr.ap-southeast-1.amazonaws.com/quyen-simpleauth-ui
  apiUrl: "/api"
  imagePullSecrets:
    - name: ecr-secret

postgresql:
  auth:
    password: StrongDBPassword123

  primary:
    persistence:
      enabled: false

  image:
    registry: 296725355870.dkr.ecr.ap-southeast-1.amazonaws.com
    repository: postgresql
    tag: latest

  imagePullSecrets:
    - name: ecr-secret

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          serviceName: simpleauth-ui
          servicePort: 80
        - path: /api
          pathType: Prefix
          serviceName: simpleauth-api
          servicePort: 80