apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-key: {{ .Values.jwt.key | b64enc | quote }}
  jwt-issuer: {{ .Values.jwt.issuer | b64enc | quote }}
  jwt-audience: {{ .Values.jwt.audience | b64enc | quote }}
  fido-domain: {{ .Values.fido.domain | b64enc | quote }}
  fido-origin: {{ .Values.fido.origin | b64enc | quote }}
  # Postgres password cũng có thể lấy từ global, nhưng tốt nhất nên dùng secret riêng
  postgres-password: {{ .Values.global.postgresPassword | b64enc | quote }}