apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "db.fullname" . }}-pvc
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}