replicaCount: 1

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

storage:
  size: 10Gi
  className: ""

service:
  port: 5432

postgresUser: authuser
postgresPassword: "ChangeMe123!"   # nên override
postgresDb: authdb

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

nodeSelector: {}
tolerations: []
affinity: {}